from helpers.repository import repo


def create_level_item(request, data, folder_name):
    engine_data = {
        "name": "NextRUSH_P",
        "version": 13,
        "tags": [],
        "title": "NextRUSH+",
        "subtitle": "NextRUSH+",
        "author": "hyeong",
        "thumbnail": repo.get_srl(request.app.files["thumbnail"]),
        "configuration": repo.get_srl(request.app.files["engine_config"]),
        "playData": repo.get_srl(request.app.files["engine_play"]),
        "watchData": repo.get_srl(request.app.files["engine_watch"]),
        "previewData": repo.get_srl(request.app.files["engine_preview"]),
        "tutorialData": repo.get_srl(request.app.files["engine_tut"]),
        "rom": repo.get_srl(request.app.files["engine_rom"]),
        "skin": {
            "name": "nextrushpskin",
            "version": 4,
            "title": "JP v3",
            "subtitle": "JP v3",
            "author": "hyeong",
            "tags": [],
            "thumbnail": repo.get_srl(request.app.files["thumbnail"]),
            "data": repo.get_srl(request.app.files["skin_data"]),
            "texture": repo.get_srl(request.app.files["skin_texture"]),
        },
        "background": {
            "name": "black",
            "version": 2,
            "title": "black",
            "subtitle": "black",
            "author": "RGB(0,0,0)",
            "tags": [],
            "thumbnail": repo.get_srl(request.app.files["thumbnail"]),
            "data": repo.get_srl(request.app.files["bg_data"]),
            "configuration": repo.get_srl(request.app.files["bg_config"]),
            "image": repo.get_srl(request.app.files["bg_image"]),
        },
        "effect": {
            "name": "v3",
            "version": 5,
            "title": "v3",
            "subtitle": "v3",
            "author": "Burrito",
            "tags": [],
            "thumbnail": repo.get_srl(request.app.files["thumbnail"]),
            "data": repo.get_srl(request.app.files["sfx_data"]),
            "audio": repo.get_srl(request.app.files["sfx_audio"]),
        },
        "particle": {
            "name": "Standard",
            "version": 3,
            "title": "Standard",
            "subtitle": "Standard",
            "author": "ToastedBread",
            "tags": [],
            "thumbnail": repo.get_srl(request.app.files["thumbnail"]),
            "data": repo.get_srl(request.app.files["particle_data"]),
            "texture": repo.get_srl(request.app.files["particle_texture"]),
        },
    }

    background = {
        "name": f"levelbg",
        "version": 2,
        "tags": [],
        "title": folder_name,
        "subtitle": f"{folder_name} Background",
        "author": "ScoreSync Modern",
        "thumbnail": repo.get_srl(request.app.files["thumbnail"]),
        "data": engine_data["background"]["data"],
        "image": repo.get_srl(data["background"]) or engine_data["background"]["image"],
        "configuration": engine_data["background"]["configuration"],
    }

    item_data = {
        "name": data["id"],
        "version": 1,
        "tags": [],
        "rating": 0.0,
        "title": folder_name,
        "artists": "???",
        "author": "you",
        "useSkin": {"useDefault": True},
        "useEffect": {"useDefault": True},
        "useParticle": {"useDefault": True},
        "useBackground": {"useDefault": False, "item": background},
        "engine": engine_data,
        "cover": repo.get_srl(data["cover"]),
        "bgm": repo.get_srl(data["music"]),
        "data": repo.get_srl(data["score"]),
    }
    return item_data
